version: '3.8'

services:
  crebito-debug:
    ports:
      - 8081:8080
    build:
      context: .
      dockerfile: ${MODE}.dockerfile
    container_name: server-debug
    volumes:
      - ./src:/src
    depends_on:
      - neo
    env_file:
      - .env
    restart: always

  neo:
    image: neo4j:latest
    ports: 
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j_data:/data/
    restart: on-failure
    environment:
      - NEO4J_AUTH=none 
      # - NEO4J_AUTH=neo4j/password
  
volumes:
  neo4j_data: