version: '3.8'

services:
  api01: &api
    build:
      context: .
    ports:
      - 8081:8080
    depends_on:
      - neo
    environment:
      - DB_HOSTNAME=neo
      - MODE=debug
      - PORT=8080
    restart: always

  api02:
    <<: *api
    ports:
      - 8082:8080

  neo:
    image: neo4j:latest
    ports: 
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j_data:/data/
    restart: on-failure
    environment:
      - NEO4J_AUTH=neo4j/password
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
  
volumes:
  neo4j_data: