version: '3.8'

services:
  crebito01: &crebito
    build:
      context: .
      # debug or prod
      dockerfile: ${ENV}.dockerfile
    hostname: server01
    container_name: server01
    ports:
      - 8081:8080
    volumes:
      - ./src:/src
    restart: always

    # TODO: Pull image to docker hub
    # image:
    # deploy:
    #   resources:
    #     limits:
    #       cpus: ""
    #       memory: ""

  crebito02:
    <<: *crebito
    hostname: server02
    container_name: server02
    ports:
      - 8082:8080

  # TODO: Nginx
  # TODO: DB