version: '3.8'

services:
  api01: &api
    build:
      context: .
    ports:
      - 8081:8080
    depends_on:
      - neo
    environment:
      - DB_HOSTNAME=neo
      - PORT=8080
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "45MB"

  api02:
    <<: *api
    ports:
      - 8082:8080

  neo:
    image: neo4j:latest
    ports: 
      - 7474:7474
      - 7687:7687
    restart: on-failure
    volumes:
      - ./db_init:/var/lib/neo4j/db_init/
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_db_lock_acquisition_timeout=30
      - NEO4J_db_relationship__grouping__threshold=10000
      - NEO4J_server_bolt_thread__pool__max__size=5000
      - NEO4J_server_bolt_thread__pool__min__size=4000
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.55"
    #       memory: "420MB"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "40MB"

networks:
  default:
    driver: bridge